### ISSUE TITLE
Clean up handling of Conventions

### ISSUE THREAD

**Issue by hagenw** [sofacoustics/sofa#7]
The conventions should be handled at a central place (maybe even in an extra repository, which would have the downside that a user would have to install two different software packages, which is not a good idea. Or we include also an automatic download of the Conventions.)

The following proposal uses only one repository for all things:

1) Remove the current `CDL` folder.
2) Replace it with a `Conventions` folder, which includes the up-to-date Convention definitions, maybe in the same format as it is currently stored in the `conventions` folder under `API_MO`
3) `API_MO` and `API_Cpp` should then use the central `Conventions` folder as a source for getting the conventions information

**Comment by petibub** [comment]
Ad 1) Agreed. CDL had a historic meaning only. 
Ad 2) definitions of conventions used by the API_MO must be within the directory structure of API_MO. 
Ad 3) I agree that having the same machine-readable definitions for all API would be nice. API_MO and API_Cpp are separate developments and they use completely different definition syntax. API_MO uses a machine-readable syntax. API_Cpp uses hard-coded C++ and header files for each conventions. Both approaches have their advantages and disadvantages...

BTW, the convention definitions are provided at different places:
- AES standard (standardized)
- sofaconventions.org (official, but not necessarily standardized yet)
- APIs (least level of standard)
